### PR TITLE
[NCLOUD-931] Add screenshots

### PR DESCRIPTION
**Pull request by dscodi**
- Added screenshots based on https://networktocode.com/apps/circuit-maintenance/

### CODE REVIEW

**Review by chadell — APPROVED** [review]
LGTM

**Comment by chadell** [comment]
@dscodi You need to document your changes in https://github.com/nautobot/nautobot-plugin-circuit-maintenance/tree/develop/changes

**Comment by dscodi** [comment]
> @dscodi You need to document your changes in https://github.com/nautobot/nautobot-plugin-circuit-maintenance/tree/develop/changes

Ok, I see that there are two files `249.added` and `249.changed`. What is the number 249, which number should I put there?

**Comment by chadell** [comment]
It's the number of the PR, 259 here

**Pull request merged**
