### PR TITLE
Nautobot 2 Migrations Rests

### PR DESCRIPTION
**Pull request by snaselj**
# Closes NaN

## What's Changed

- Changed to use `NautobotAppConfig`.
- Changed imports from `extras` to `apps`.
- Updated dependencies to better match RC versions.
- Removed unused Python 3.7 dependencies and imports.
- Removed unused `google-oauth` dependency.

## To Do

- [x] IMPORTANT `poetry.lock` is not up to date, after releasing Capacity Metrics `3.0.0rc3`, it needs to be updated with `poetry lock --no-update`. https://github.com/nautobot/nautobot-plugin-capacity-metrics/pull/57

### CODE REVIEW

**Comment by snaselj** [comment]
cc @bryanculver

**Comment by snaselj** [comment]
Rebased on top of the latest `next-2.0` to resolve conflicts. Ready to go.

**Comment by chadell** [comment]
@snaselj could we solve "Removed unused google-oauth dependency." in `develop`?

**Review by chadell — APPROVED** [review]
LGTM

**Pull request merged**
