### PR TITLE
Implemented CI workflow in GH Actions

### PR DESCRIPTION
**Pull request by ubajze**

### CODE REVIEW

**Comment by ubajze** [comment]
FYI: When this PR is merged, we need to delete the old PyPI token.

**Comment by chadell** [comment]
> FYI: When this PR is merged, we need to delete the old PyPI token.

Do you mean that you have already rotated it and updated in the secrets backend?

**Comment by ubajze** [comment]
> > FYI: When this PR is merged, we need to delete the old PyPI token.
> 
> Do you mean that you have already rotated it and updated in the secrets backend?

Correct. Also tested publishing and it works. This PR is ready to be merged.

**Review by chadell — APPROVED** [review]
LGTM

**Pull request merged**
