### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by glennmatthews**

### CODE REVIEW

**Review by chadell — DISMISSED** [review]
LGTM

**Comment by glennmatthews** [comment]
Stand by before merging this - I have one more upcoming PR I'd like to get into this release. Thanks!

**Comment by glennmatthews** [comment]
See https://github.com/nautobot/nautobot-plugin-circuit-maintenance/pull/156

**Review by chadell — APPROVED** [review]
LGTM

**Pull request merged**
